# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u540d\u79f0')),
                ('file_path', models.CharField(max_length=150, verbose_name='\u6587\u7ae0\u8def\u5f84')),
                ('file_md5', models.CharField(max_length=32, verbose_name='\u6587\u7ae0MD5')),
                ('file_fence', models.TextField(verbose_name='\u6587\u7ae0\u5206\u8bcd')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u4fe1\u606f',
                'verbose_name_plural': '\u6587\u7ae0\u4fe1\u606f',
            },
        ),
    ]
