# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='is_fen',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5206\u8bcd'),
        ),
    ]
